CREATE TABLE SUPPORT_TICKETS(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   CUSTOMER_NAME TEXT NOT NULL,
   PRIORITY TEXT,
   ISSUE_SCORE REAL
 );
 
INSERT INTO SUPPORT_TICKETS(CUSTOMER_NAME,PRIORITY,ISSUE_SCORE) VALUES
('Dana','high',95),
('Omer','medium',74),
('Noa','high',88);

SELECT*
FROM SUPPORT_TICKETS
WHERE PRIORITY = 'medium';

INSERT INTO SUPPORT_TICKETS(CUSTOMER_NAME,PRIORITY,ISSUE_SCORE) VALUES ('Liam','low',80);

SELECT * FROM SUPPORT_TICKETS;

DELETE FROM SUPPORT_TICKETS
WHERE CUSTOMER_NAME = 'Noa';
